### ISSUE TITLE
Remove need for --replicate flags

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/kube-mgmt#10]
The policies should be analyzed to determine which Kubernetes resources to replicate into OPA.

For example, given a policy like:

```
package kubernetes.admission

import data.kubernetes.resources.namespaces
import data.kubernetes.resources.pods

deny[msg] { ... }
```

We could establish a convention that Kubernetes data is inserted at a specific path (e.g., `kubernetes.resources`.) Then the policies could be analyzed to determine which resource kinds are required.

**Comment by sandeepbhojwani** [comment]
This will be very cool. Any updates on this?

**Comment by tsandall** [comment]
There hasn't been any work done on this to date. We'll keep it mind as we prioritize things for the next few months.

**Comment by shasti86** [comment]
Do we still need this feature? Does gatekeeper support this already? @tsandall

**Comment by tsandall** [comment]
@shasti86 it's not implemented in gatekeeper AFAIK. It would be nice to have however it's not a priority.
