### ISSUE TITLE
Add examples for easier use of kube-mgmt with OPA

### ISSUE THREAD

**Issue by shrinandj** [open-policy-agent/kube-mgmt#12]
kube-mgmt with OPA can be very powerful for operating Kubernetes clusters at scale in large companies. Policies can enforcing company specific compliance rules or Initializers can directly injecting required parameters into the Kubernetes objects. However, it is currently hard to discover and quickly get off the ground with this setup. The only document I found was this [webpage](http://www.openpolicyagent.org/docs/kubernetes-admission-control.html) on the website. That too is limited in its utility since it does not talk about RBAC.

Along with the official documentation, it will be better to have an example directory with complete (directly usable) examples to get started.

**Comment by tsandall** [comment]
@shrinandj we'll happily take examples.

Also, if you think the admission control tutorial on the web page could be updated to work with RBAC that would be a welcome contribution as well.  The source for the tutorial is here: https://github.com/open-policy-agent/opa/blob/master/docs/book/kubernetes-admission-control.md

Closing this issue for now. Feel free to submit PRs w/ your examples.
