### ISSUE TITLE
[helm] Make dns policy configurable

### ISSUE THREAD

**Issue by stevo-f3** [open-policy-agent/kube-mgmt#130]
When opa Deployment is run on host network, dns policy should typically be set to `ClusterFirstWithHostNet` (see https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy)

Please make dns policy configurable in helm chart and default to `ClusterFirstWithHostNet` when host network is enabled.

https://github.com/open-policy-agent/kube-mgmt/blob/master/charts/opa/values.yaml#L116
https://github.com/open-policy-agent/kube-mgmt/blob/master/charts/opa/templates/deployment.yaml#L81-L83

**Comment by anderseknert** [comment]
Seems reasonable to me. Would you want to submit a PR?

**Comment by stevo-f3** [comment]
@anderseknert PR is up https://github.com/open-policy-agent/kube-mgmt/pull/138
