### ISSUE TITLE
Require Linux/ARM64 docker image for open-policy-agent/kube-mgmt 

### ISSUE THREAD

**Issue by odidev** [open-policy-agent/kube-mgmt#143]
Hi Team,     

I have been working on building open-policy-agent/kube-mgmt docker image for the arm64 platform and I have successfully built the docker image for the arm64 platform locally and it is working fine.  

Do you have any plans for releasing arm64 images?  I’m happy to help if needed.

**Comment by anderseknert** [comment]
Contributions would definitely be welcome! Ideally we'd have the same image published for multiple targets, like we do for the OPA `-static` image.

**Comment by odidev** [comment]
I have made some changes in Dockerfile, release.yaml and justfile to build and release docker images using buildx. 

 

Commit Link:- https://github.com/odidev/kube-mgmt/commit/8d2d021e6b8e41b99ab8a9b6e34a052a74c69eb1 

 

If these changes are ok, then I will raise the PR.

**Comment by anderseknert** [comment]
Looks fine to me, but let's open that PR and we can continue the discussion with more participants there :)
