### ISSUE TITLE
Enable ARM64 testing in Github Actions

### ISSUE THREAD

**Issue by odidev** [open-policy-agent/kube-mgmt#155]
Currently, there are only AMD64 test jobs available on github actions. It will be useful if we add test jobs for ARM64 as well in github actions, as it is better to test before releasing ARM64 docker images. 

We can do ARM64 testing in Github actions using self-hosted arm64 runners. 

If interested, we can get access to ARM H/W through [WorksOnArm](https://github.com/WorksOnArm).

**Comment by odidev** [comment]
Hi Team,

Adding a gentle reminder to take a look into this issue.

**Comment by eshepelyuk** [comment]
https://opensource.guide/how-to-contribute/
