### ISSUE TITLE
Add support for loading policies via CRDs

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/kube-mgmt#16]
Some users have requested the ability to load policies into OPA via CRDs. Creating an issue to track the work.

- Define new CRD to contain OPA policies (e.g., policy.openpolicyagent.org/v1beta1)
- Implement controller in kube-mgmt similar to configmap controller that loads policies into OPA
- Add flag to kube-mgmt to switch policy loading from configmaps to CRDs
- Update documentation to refer to CRDs (including recommended RBAC configuration)

**Comment by eshepelyuk** [comment]
Lets close it,  3 yrs passed and no feedback on this issue from community.

**Comment by richardjennings** [comment]
@eshepelyuk out of curiosity, why was there no feedback on this ? Having a CRD might provide for some more advanced use-cases oriented around admission control.

**Comment by eshepelyuk** [comment]
right now, its 6 yrs w/o feedback from OP
