### ISSUE TITLE
Bad indents: can't specify resources for mgmt

### ISSUE THREAD

**Issue by kleug** [open-policy-agent/kube-mgmt#168]
https://github.com/open-policy-agent/kube-mgmt/blob/6e4a2f4005fa336f48098c2208e930a14f2c1620/charts/opa-kube-mgmt/templates/deployment.yaml#L166

This line cause release failed for me i think it's should be like line 99 with no space if you specify indent
i can't specify ressource for mgmt

https://github.com/open-policy-agent/kube-mgmt/blob/6e4a2f4005fa336f48098c2208e930a14f2c1620/charts/opa-kube-mgmt/templates/deployment.yaml#L99

**Comment by eshepelyuk** [comment]
Hello @kleug 
The fix is available at 7.0.7, thanks for a contribution.
