### ISSUE TITLE
Helm chart does not support Kubernetes v1.25 PodDisruptionBudget

### ISSUE THREAD

**Issue by elchenberg** [open-policy-agent/kube-mgmt#171]
Kubernetes v1.25 removed the deprecated apiVersion `policy/v1beta1` for PodDisruptionBudgets that is used in the Helm chart: https://github.com/open-policy-agent/kube-mgmt/blob/5d94d2971df897fe6a0e54e7f8c7ac5dea690961/charts/opa-kube-mgmt/templates/poddisruptionbudget.yaml#L2-L3

Installing the chart fails with the following error: `no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"`.

**Comment by eshepelyuk** [comment]
Thnx for contribution @elchenberg 
Available in https://github.com/open-policy-agent/kube-mgmt/releases/tag/7.0.8
