### ISSUE TITLE
CVE reported on kube-mgmt v8.0.1 - libcrypto1.1

### ISSUE THREAD

**Issue by porwalameet** [open-policy-agent/kube-mgmt#191]
HI Team, trivy (https://aquasecurity.github.io/trivy/v0.18.3/) reported 2 high CVE on latest kube-mgmt

kube-mgmt version: 8.0.1
Trivy command: trivy image openpolicyagent/kube-mgmt:8.0.1

![trivy-kube-mgmt-cve](https://user-images.githubusercontent.com/25053539/223044659-82b54382-ee19-40c8-8de9-4a5dde69839b.png)

Expected Results:
- No CVE have to alerted

Actual Results:
- 2 High CVEs are reported in the scan

**Comment by farhan1094** [comment]
Opened a #219 to resolve the above. Sorry for the multiple closed PRs - the DCO check gave me some trouble.
