### ISSUE TITLE
CVE reported for gopkg.in/yaml.v3

### ISSUE THREAD

**Issue by kunhwiko** [open-policy-agent/kube-mgmt#199]
Hello Team, our JFrog scan reported 3 high CVEs for kube-mgmt version 8.1.0

![Screenshot 2023-04-06 at 1 39 50 PM](https://user-images.githubusercontent.com/55007166/230489482-ab89111f-86ec-4326-afe3-69695fa36822.png)

I do think that the vulnerability for golang.org/x/net has been resolved in the master branch (are there any plans to have a new release version soon?), but at the same time, wondering if it is possible to look into the vulnerability for gopkg.in/yaml.v3

**Comment by eshepelyuk** [comment]
Hello @kunhwiko 
PRs are welcome

**Comment by saranyareddy24** [comment]
Working on it.

**Comment by eshepelyuk** [comment]
@saranyareddy24 maybe you're willing to also take a look at #191 ?
