### ISSUE TITLE
When OPA container restarted kube-mgmt is not re-syncing the policies

### ISSUE THREAD

**Issue by saranyareddy24** [open-policy-agent/kube-mgmt#207]
Hi,

As part of our resiliency testing to test liveness and readiness probe for OPA container, we intentionally made the OPA container down which resulted in the restart of OPA container. When the OPA container came back there was an error seen in OPA container logs 
` "error": {
    "code": "undefined_document",
    "message": "document missing: data.system.main"
  },`
This is because kube-mgmt didn't reload the policies to OPA as it couldn't identify that OPA container restarted.
As a result of this we are seeing below error in other application logs
failed calling webhook `"[mutating-webhook.openpolicyagent.org](http://mutating-webhook.openpolicyagent.org/)"`

kube-mgmt should be able to identify the restarts of OPA container and reload the policies to avoid hitting this issue.

**Comment by saranyareddy24** [comment]
Can anyone please look into this issue.

**Comment by eshepelyuk** [comment]
Duplicare of #189
