### ISSUE TITLE
CVE Vulnerabilities

### ISSUE THREAD

**Issue by farhan1094** [open-policy-agent/kube-mgmt#209]
The following fixable vulnerabilities are present in the latest image of kube-mgmt repo:

<img width="822" alt="image" src="https://github.com/open-policy-agent/kube-mgmt/assets/92339155/a647b01b-4312-4a39-b54e-717befe5da50">

**Comment by eshepelyuk** [comment]
Hello @farhan1094 

PR is welcome.

**Comment by eshepelyuk** [comment]
duplicate of #191
