### ISSUE TITLE
auth token should not be listed on command line

### ISSUE THREAD

**Issue by gnealhou** [open-policy-agent/kube-mgmt#23]
This is an enchancement request.

**CURRENT STATE**

The opa authentication token is passed in via command line with the --opa-auth-token command. This means OPA can be compromised by:

- anyone with access to the Kubernetes Deployment (kubectl get deploy -n opa <deployment name> -o yaml)
- anyone with access to the kube-mgmt pod (kubectl get pod -n opa <podname> -o yaml)
- anyone with exec privileges on the kube-mgmt pod

**DESIRED STATE**

For security reasons, provide a more secure authentication mechanism (TLS) or reduce access to the authentication token. To make authentication tokens more secure:
- the authentication token should be stored and optionally encrypted in a Kubernetes secret and mapped to kube-mgmt's filesystem
- kube-mgmt takes a command-line argument indicating the location of the auth token file
- kube-mgmt takes a command-line argument indicating the decryption key (optional -- no argument indicates the auth token file is not encrypted).

**ALTERNATIVES**

The following alternatives lower or eliminate the need for this enchancement request:
- Support TLS encrypted communications between kube-mgmt and OPA with both services presenting and verifying certificates.
- Document an OPA authorization policy that validates policy change requests come from the IP address (localhost?) of the kube-mgmt container.
- Anything else that removes the authentication token from the command line, Kubernetes deployment, and Kubernetes pod.

**Comment by tsandall** [comment]
It may be possible to refer to an environment variable in the command line arguments and then load the secret that way. I'll try this out and reply here. If that doesn't work, perhaps we ought to let users specify the token via environment variables. That seems like the simplest approach for now.

RE: mutual TLS, OPA does not currently support that in the HTTP server. We have an open issue for this https://github.com/open-policy-agent/opa/issues/1040.

**Comment by gnealhou** [comment]
Either would work -- storing the token in an environment variable means the Kubernetes deployment can keep it in a Secret. If someone can get on the pod to view the environment, they can probably get the secret if it's in a file, too.

**Comment by ashutosh-narkar** [comment]
I am going to try to use the secret in an environment variable and use that env variable in the command line. Will update here. But as @gnealhou mentioned the secret will be visible on entering the kube-mgmt pod.

**Comment by gnealhou** [comment]
Much better. The token is out of multiple kubernetes objects (that lots of
people could see) and hidden from a casual glance if someone gets on the
box. Assuming we apply appropriate policies to the kube-mgmt container (no
network access, no exec access), it's reasonably secure.

Gary

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ashutosh-narkar** [comment]
Closing this as the auth token is reasonable secure and no longer listed on the command line.

**Comment by kfox1111** [comment]
reading it out of a file would also be very useful.

**Comment by ashutosh-narkar** [comment]
@kfox1111 someone with access to the container can still see the token, right ?
