### ISSUE TITLE
Alpine 3.16 is running out of support by May 2023

### ISSUE THREAD

**Issue by degrammont** [open-policy-agent/kube-mgmt#247]
Alpine 3.16 is running out of support by May 2023, is there a plan to upgrade to newer Alpine version for the base image?

**Comment by eshepelyuk** [comment]
> Alpine 3.16 is running out of support by May 2023, is there a plan to upgrade to newer Alpine version for the base image?

Hello
There were no certain plans, but PRs are always welcome.
