### ISSUE TITLE
Not possible to add extra container ports

### ISSUE THREAD

**Issue by Skoucail** [open-policy-agent/kube-mgmt#256]
I'm trying to use this helm chart to deploy OPA-envoy with kube-mgmt.
With the properties extraArgs and extraPorts i was able to pass in the envoy plugin settings and expose the GRPC port in the created serice.

But the problem is that there is no option to expose the pods port.
My values:
![image](https://github.com/user-attachments/assets/867dc472-6d73-42a4-adc8-6c7d083afd4a)

The created deployment contains:
![image](https://github.com/user-attachments/assets/c14a2611-5025-4641-95ae-a0bc5e3cf6ee)

I didn't find any way to also add a containerPort in the ports section to expose the GRPC port 9191

**Comment by anderseknert** [comment]
@ievgenii-shepeliuk , any idea?

**Comment by eshepelyuk** [comment]
@Skoucail is right, there's no way to specify extra ports for `opa` container.
So, PRs are welcome.

**Comment by eshepelyuk** [comment]
@Skoucail `extraPorts` are adding ports to the K8s `Service`, and AFAIR - if ports are physically exposed in container, then it should work, if you are not using named ports, but just numbers of a port.

Am I wrong ?

**Comment by Skoucail** [comment]
@eshepelyuk 
Thanks for the clarification.
I started over from 0 and now it works. I must have made an error somewhere.
