### ISSUE TITLE
OPA image in Helm chart is outdated

### ISSUE THREAD

**Issue by EdwardCooke** [open-policy-agent/kube-mgmt#263]
In the Helm chart you default to 0.53.1. However, the latest stable release of OPA is 0.69.0. With itt being outdated it means its not compatible with latest docs, like being able to `import rego.v1`.

**Comment by eshepelyuk** [comment]
Hello, @EdwardCooke 

* you can always override OPA version via [Helm values](https://github.com/open-policy-agent/kube-mgmt/blob/master/charts/opa-kube-mgmt/values.yaml#L115)
* If you're willing to provide a PR for this issue - welcome

**Comment by EdwardCooke** [comment]
PR created.
