### ISSUE TITLE
Fail when "error(s) occurred while compiling module(s)"

### ISSUE THREAD

**Issue by yuzhouliu9** [open-policy-agent/kube-mgmt#267]
Running OPA 0.54.0 and kube-mgmt v8.3.0

We frequently see errors like these from kube-mgmt
```
level=info msg="Added policy opa/opa-istio-whitelist-rego-policy/opa-istio-whitelist.rego, err=code invalid_parameter: error(s) occurred while compiling module(s)"
```

It is a problem from our .rego that we will address.

But the issue is that kube-mgmt container continues on even with the error. The rules we've defined are not enforced on this OPA pod.
Is there a way to fail the container when this error occurs?

**Comment by eshepelyuk** [comment]
there is no way to _fail kube-mgmt container, whatever you mean with _fail_.

**Comment by yuzhouliu9** [comment]
The behavior we observe is that when the invalid_parameter error occurs, the .rego defined is not enforced. Thus defeating the purpose of having OPA.

kube-mgmt container should restart or error. This is a better signal than just logging this error.

**Comment by eshepelyuk** [comment]
if `kube-mgmt` pod restarts on such error, it will re apply the same incorrect OPA from the `ConfigMap` and receive the same error 

So, what is the purpose of restart ?

**Comment by yuzhouliu9** [comment]
It will signal to the operator something is wrong, rather than having to parse logs for this specific error.

Think of it from a user perspective:

1. A single error line occurs in kube-mgmt container. OPA rules for that .rego is not enforced.
2. OPA pod is ready, starts serving requests. Lots of logs generated indicating all is well, and that single log is buried.
3. Then one day a request that was supposed to be denied by OPA is allowed in. The operator has to look through all the OPA logs to find that one line from 60 days ago when kube-mgmt started to find the cause.

**Comment by yuzhouliu9** [comment]
If there are multiple OPA pods, does `openpolicyagent.org/kube-mgmt-status` annotation get stomped?

**Comment by eshepelyuk** [comment]
> If there are multiple OPA pods, does `openpolicyagent.org/kube-mgmt-status` annotation get overwritten by newer pods?

kube mgmt doesn't support scaling opa pods
https://github.com/open-policy-agent/kube-mgmt/issues/194

**Comment by eshepelyuk** [comment]
This is OSS 
You're always welcome to address the issue by providing PR.
