### ISSUE TITLE
[CHART] Webhook changes recreates secret which results in TLS error:

### ISSUE THREAD

**Issue by Nheijmink19** [open-policy-agent/kube-mgmt#268]
Changing the webhook sometimes results into the creation of a new certificate and because of that an updated secret.
The updated secret introduces the following error:

`tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "opa-admission-ca")`

The secret is updated in the pod since kubernetes automaically updates mounted secrets and configmaps, but the OPA process does not reload the secrets. After restarting the pods the issue is solved.

The small change in the deployment  created at this fork solves the issue:
https://github.com/open-policy-agent/kube-mgmt/compare/master...Sir-Jacques:kube-mgmt:master

**Comment by Sir-Jacques** [comment]
I've created the PR, issues can be closed.
