### ISSUE TITLE
OPA TLS based client authentication with kube-mgmt

### ISSUE THREAD

**Issue by sandeepsharmadevops** [open-policy-agent/kube-mgmt#40]
OPA authentication supports bearer token and TLS based.

- referencing document is available when OPA is configured with token-based authN and kube-mgmt, but what if OPA is configured with TLS base authN, in that case how kube-mgmt gets authenticated by OPA, does mgmt support any other cmd line flag to be passed
if yes please suggest with an example if possible
if not guide me about the solution considering we want to opt for TLS based authN within OPA, how mgmt authentication can be handled by OPA

**Comment by manicole** [comment]
Is it still pending, or is the TLS based authn available in recent releases ? Thanks

**Comment by tsandall** [comment]
kube-mgmt only supports token-based auth/n at this point in time. Single machine-vs-within Kubernetes should not matter since it's the Go HTTP client that needs to be configured w/ a client certificate in order for TLS-based authentication to be used.

**Comment by manicole** [comment]
OK I understand, thanks for answering :)
