### ISSUE TITLE
kube-mgmt is not recompiling/rechecking the syntactical issues

### ISSUE THREAD

**Issue by sandeepsharmadevops** [open-policy-agent/kube-mgmt#41]
Hi @tsandall ,

Facing one strange issue, where for example i have deployment one configmap rego policy which then compiled and validated by kube-mgmt and loaded into opa server and annotated with status OK.

Post above if i made any syntactical error(intentionally just to validate) in the loaded policy by using kubectl edit configmap command, kube-mgmt annotate the status with ERROR, which is as per normal behaviour of kube-mgmt, but i observed below issues.

1. any new policy configmap does not get annotated by kube-mgmt with respect to its status and also it does not gets applied by opa.
2. even if i rollback/revert the syntactical error made earlier, but status would remain the same with ERROR.

In order to overcome above issues, i have to restart the opa deployment.

I checked the opa & mgmt logs as well, didn't find anything suspicious.

Please guide me here with your expertise.

Thx,
Sandeep

**Comment by sandeepsharmadevops** [comment]
@tsandall observations:

Version:
- opa = 0.10.7
- mgmt = 0.8
- working status = working fine without any issue

Version:
- opa = 0.11.0
- mgmt = 0.8
- working status = facing described issue.

**Comment by tsandall** [comment]
@sandeepsharmadevops that's surprising. I'll try to reproduce this problem in the next day or so. It sounds like updates to the configmap are not being propagated, but I'll need to turn on debug logging in OPA to check.

**Comment by tsandall** [comment]
@sandeepsharmadevops thanks for filing this. This issue uncovered a bug in the OPA server that was introduced between v0.10.7 and v0.11.0. There will be a v0.11.1 release cut in the next day or so that resolves the problem.

**Comment by sandeepsharmadevops** [comment]
thanks @tsandall for addressing this promptly, awaiting for opa server bug fix release

**Comment by tsandall** [comment]
This is fixed in v0.12.0 which was released earlier this afternoon.

**Comment by sandeepsharmadevops** [comment]
Thanks @tsandall for providing this very prompt release, i will validate it and confirm you.

Thanks again!!!!

**Comment by sandeepsharmadevops** [comment]
Hi @tsandall  today i validated the latest opa release(0.12.0), working at first glance, i will share in case anything comes up during detailed implementation.

thanks.
