### ISSUE TITLE
Move to Go modules?

### ISSUE THREAD

**Issue by miekg** [open-policy-agent/kube-mgmt#47]
Hi, is there any appetite to move to Go modules? We use it for CoreDNS and works quite well.

Happy to send a PR that deletes 1M files :)

**Comment by patrick-east** [comment]
I think in general most of the opa projects are looking to get away from glide and move to modules as they mature (with some landing on dep along the way).  I would be surprised if there was much in the way of push back if you put up that PR 😄

**Comment by srenatus** [comment]
Looks like this was done, thanks to @rg2011.
