### ISSUE TITLE
Add flag to automatically generate admission CA and server cert

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/kube-mgmt#5]
When kube-mgmt is deployed and automatically registers OPA as an admission controller, it would be nice if it would take care of generating the CA and server cert (and making the latter available to OPA) as this is currently done manually. This should be an optional feature that users can enable using a command line argument.

**Comment by gordonbondon** [comment]
Maybe you can leverage `cert-manager` here. They have a way to bootstrap certificates for webhooks and updating them in admission controller configuration: https://github.com/jetstack/cert-manager/blob/master/contrib/manifests/cert-manager/with-rbac-webhook.yaml
