### ISSUE TITLE
periods of missing data

### ISSUE THREAD

**Issue by rtoma** [open-policy-agent/kube-mgmt#52]
Hi,

We run OPA 0.13.2 and kube-mgmt 0.10 with replication of namespaces, services and ingresses. It is a 6 pod deployment on GKE 1.13.x. We upgraded kube-mgmt from 0.8 to 0.10 yesterday. To verify this upgrade we first added a custom metrics exporter that counts the result items in /v1/data/kubernetes/{namespaces,ingresses,services}.

Analysing the metrics today it seems we have gaps in the OPA data. The following graph shows the spread between the lowest number of data items found versus the highest number. This line should be zero indicating all pods have the same number of data items.
![image](https://user-images.githubusercontent.com/2914051/67091922-3b1ef980-f1ae-11e9-9416-17ec9aaa60af.png)

When looking at a single incident. I see the namespace count in a single OPA pod drops from 554 to 0. Then goes slowly to 1, 2, 3 and finally jumps back to 554. All of this over a period of 12 minutes. See graph below to illustrate this gap. Other incidents took longer, but all auto recovered.
![image](https://user-images.githubusercontent.com/2914051/67092179-ddd77800-f1ae-11e9-886b-dd2d3dedebfc.png)

To verify our metrics are to be trusted I did REST API calls to the affected OPA container. The metrics are correct.
```
$ curl -ks https://0:1443/v1/data/kubernetes/namespaces | jq '.result|keys' wc-l
      3
```

After recovery (which can be triggered by killing the kube-mgmt process) I see:
```
$ curl -ks https://0:1443/v1/data/kubernetes/namespaces | jq '.result|keys'|wc -l
     546
```

I did report this issue earlier when using kube-mgmt 0.9 and the fix ought to be present in 0.10 - but it clearly is not.

Logging of kube-mgmt show these events, but based on other issues I assume they are not related:
```
opa-internal-7f98c9546f-2vmxn kube-mgmt E1018 08:29:30.686185       1 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: no kind "Status" is registered for version "v1" in scheme "github.com/open-policy-agent/kube-mgmt/pkg/configmap/configmap.go:102"
```
... and ...
```
opa-internal-7f98c9546f-2vmxn kube-mgmt time="2019-10-18T10:35:30Z" level=info msg="Sync channel for v1/namespaces closed. Restarting immediately."
opa-internal-7f98c9546f-2vmxn kube-mgmt time="2019-10-18T10:35:30Z" level=info msg="Syncing v1/namespaces."
opa-internal-7f98c9546f-2vmxn kube-mgmt time="2019-10-18T10:35:31Z" level=info msg="Listed v1/namespaces and got 544 resources with resourceVersion 720115319. Took 507.146764ms."
```
Logging of OPA is just full of normal stuff.

I do see a few PUT data requests, which result in the slow increase of namespace items . Like:
```
opa-internal-7f98c9546f-2vmxn opa {"client_addr":"127.0.0.1:45916","level":"info","msg":"Received request.","req_id":116,"req_method":"PUT","req_path":"/v1/data/kubernetes/namespaces/sdrtdfuygiu","time":"2019-10-18T11:12:21Z"}
```

We've rolled back to kube-mgmt 0.8 for the time being. Knowing that version does slow data pumping (~5 minutes for all the data to be PUT to OPA) and has a sync bug (deleted k8s resources do not always get deleted in OPA).

**Comment by patrick-east** [comment]
Any chance you can provide logs from kube-mgmt and OPA during one of the events where it drops to 0 and then recovers?

I'm primarily curious to see what kube-mgmt was doing when it dropped them to 0, and anything between then and pushing the data back. The OPA logs should help confirm when the API calls that were happening to clear the data occurred.

**Comment by rtoma** [comment]
OPA is spewing serious amounts of logging, so we generally do not keep more logs than what Kubernetes does (not much). But we do have the OPA internal metrics exposed. When looking at it, I see calls to the webhook endpoint (POST on /) stop at the same time the OPA data is cleared.

As you may know makes the API server direct connections to OPA pods and not via the service. For efficiency these connections are long lasting and the API server tends to keep open 1 or 2 of such connections. This bit of information is required to interpret the following graph correctly:
![image](https://user-images.githubusercontent.com/2914051/67140957-7299ae80-f25f-11e9-866f-b99e2a503a6d.png)

Interpreting the above graph:
- the orange line (pod "l5gj2") stops at 01:15
- the blue line (pod "b7w4g") stops at 03:45
- the orange line (pod "l5gj2") stops at 06:34

These times AND the pods correlate with the data drops:
![image](https://user-images.githubusercontent.com/2914051/67141033-197e4a80-f260-11e9-8e42-1ae56127bc51.png)

So I am wondering:

1. why does the API server stop using a specific pod? (just time to cycle, timeout or error?)
2. is there a race condition in OPA between a webhook call and a data update? (we saw this behaviour before our data metrics, so I am excluding that as a cause for now)

My current hypothesis: there is an issue in OPA triggered by use of the syncAll call in kube-mgmt.

I will dig deeper and try to find proof. Hopefully I have given you some breadcrumbs to zero in on a possible cause. Share any ideas and we'll find the root cause together.

**Comment by rtoma** [comment]
Even though I have not caught errors in the OPA logs, I do see OPA containers being restarted within the pod (kube-mgmt is not restarted), so that indicates issues with OPA. And the fact that the API server picks another pod at the same time supports the theory that OPA containers panic.

So I am now testing with OPA 0.13.5 (including some panic fixes) and kube-mgmt 0.10 right now.

🤞

**Comment by patrick-east** [comment]
Looking forward to hear if 0.13.5 helps.

> I do see OPA containers being restarted within the pod (kube-mgmt is not restarted), so that indicates issues with OPA.

Another thing to check on/rule out is that the liveness probe for OPA didn't timeout. I have seen issues with that where OPA is under load and has too short of a timeout configured for the liveness probe. End result is similar where the OPA pods restart for no immediately apparent reason.

**Comment by rtoma** [comment]
OPA 0.13.5 with kube-mgmt 0.10 still going strong after 10 hours. In this timespan we would have seen multiple API server reconnects (changes in what OPA pods handle the load), trigger by OPA pod panics. No such thing today:
![image](https://user-images.githubusercontent.com/2914051/67229108-ee038780-f43a-11e9-99e9-ddc857f13474.png)

In our case the liveness probes can be ruled out. Failing probes are included in the `kubectl get event` stream and there are none.

**Comment by rtoma** [comment]
Closing this issue. Upgrading OPA from 0.13.2 to 0.13.5 fixed the panics.
