### ISSUE TITLE
Automatic policy removal using ConfigMap's label

### ISSUE THREAD

**Issue by alebedev87** [open-policy-agent/kube-mgmt#61]
Hello,

I can see that the policy is removed from OPA if the corresponding ConfigMap is deleted.
However, I expected the same behavior when I simply remove `openpolicyagent.org/policy=rego` label from the policy's ConfigMap.

Can you please advice whether the removal by label is intentionally disabled or not?

kube-mgmt version: 0.10
Flags used:
```
args:
    - "--policies=my-opa"
    - "--enable-data"
    - "--require-policy-label"
```
Kubernetes version: v1.11.0+d4cacc0 (via OpenShift v3.11.0+0cbc58b)

If the use case I described looks like a good idea to you, I created [this PR](https://github.com/open-policy-agent/kube-mgmt/pull/62).

Thank you,
Andrey

**Comment by tsandall** [comment]
Fixed by #62.
