### ISSUE TITLE
Customize configmap policy label key/value

### ISSUE THREAD

**Issue by prabushyam** [open-policy-agent/kube-mgmt#88]
We have a setup to run OPA validating and mutating webhooks as two different k8s deployments. Now, we would want the policy configmaps for validating and mutating hooks to be distinguished. Unfortunately the configmap label key/value is [hard-coded](https://github.com/open-policy-agent/kube-mgmt/blob/c1e29c8f0e40dfa392e9d085d879783102b1984a/pkg/configmap/configmap.go#L27-L29) and both OPA instances load all the validating & mutating configmaps. Could we add a CLI option to specify the policy label key & value to look for?

**Comment by tsandall** [comment]
@prabushyam that sounds reasonable to me! If you want to submit a PR, feel free! Just make the sure the default for the CLI option is the same as the current so that users aren't impacted when they upgrade.

**Comment by kirk-patton** [comment]
https://github.com/open-policy-agent/kube-mgmt/pull/89
