### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by edify42** [open-policy-agent/kube-mgmt#91]
Sorry to annoy, but would love to see a new helm chart released with this merged change https://github.com/open-policy-agent/kube-mgmt/pull/86

:heart:

**Comment by edify42** [comment]
Tagging @tsandall

**Comment by tsandall** [comment]
! Happy to cut a release. For the helm update, does anything have to happen beside bumping this value? https://github.com/open-policy-agent/kube-mgmt/blob/master/charts/opa/values.yaml#L126

**Comment by edify42** [comment]
Hey @tsandall ! Thanks for your fast response :)

It's actually to include this line: https://github.com/open-policy-agent/kube-mgmt/blob/master/charts/opa/templates/webhookconfiguration.yaml#L3

Our k8s setup uses k8s 1.19 which is built with a newer version of Golang that deprecated some legacy x509 certificate config. Another issue i dug up has seen a similar problem: https://github.com/kubeflow/katib/issues/1395

**Comment by phisco** [comment]
Hi @edify42, we will cut 0.12.1 right away.

**Comment by phisco** [comment]
Hi @edify42, the new helm chart should be available, still version 1.14.6 of the chart (we have to decide the versioning policy of the chart).
Please give it a go and let us know.

**Comment by edify42** [comment]
Thanks all! Works a treat now :+1:
