### ISSUE TITLE
Availability of metrics for kube-mgmt

### ISSUE THREAD

**Issue by HarshitaJha** [open-policy-agent/kube-mgmt#92]
This is a question, not an issue.
I am trying to monitor the OPA running on my K8s cluster via prometheus and grafana. Can you please tell me if there are metrics for kube-mgmt? Are they exposed on the metrics endpoint to be scraped by Prometheus?

**Comment by phisco** [comment]
Hi @HarshitaJha, let me better understand, do you mean you are already aware of the `/metrics` endpoint exposed by open-policy-agent and would like to know if kube-mgmt is exposing its own metrics at some endpoint or via the same endpoint in some way?

**Comment by HarshitaJha** [comment]
Yes, I am aware of the /metrics endpoint at which OPA exposes its metrics. I want to know if kube-mgmt also exposes its own metrics on the same endpoint or some endpoint. Please clarify on this.

**Comment by phisco** [comment]
AFAIK there is none and after a quick search, I couldn't find any reference to metrics being exposed by kube-mgmt directly. Maybe @tsandall could help.
What kind of metrics would you be interested in kube-mgmt exposing?

**Comment by tsandall** [comment]
kube-mgmt doesn't expose a /metrics endpoint because it's essentially stateless and just watches configmaps and other kubernetes resources and replicates them into OPA. It doesn't even expose an HTTP server today.

**Comment by phisco** [comment]
That was my understanding and expectation, thanks @tsandall.
@HarshitaJha I think we can close this issue, if you have any suggestion about metrics you'd like to have exposed by kube-mgmt feel free to write them down here.

**Comment by HarshitaJha** [comment]
Thanks for the clarification @phisco and @tsandall .
