### ISSUE TITLE
Deployment issue with generateAdmissionControllerCerts

### ISSUE THREAD

**Issue by hochuenw-dd** [open-policy-agent/kube-mgmt#96]
Hi,
Users can use `generateAdmissionControllerCerts ` to ask the chart to generate the certs for them during the deploy. So it seems every new deploy will use new certs when this flag is true? 
If this is the case, I'm wondering if this will cause some issues.
During the deploy, depends on how the maxUnavailable is set, you may have some new pods using new certs and old pods using old certs.
If the opa is deployed in a large cluster, what could happen is that at the same time, the caBundle in the validatingwebhookconfiguration is updated, which cause the requests to the old pods fail. The new olds are overloaded by the requests and start crashing. So this may cause all requests to OPA fail. 

I might miss something here. Is this true? Thanks!

**Comment by phisco** [comment]
Hi @hochuenw-dd, I'm pretty sure the generated CA and cert are not generated again for a single release, but I should test it.

Did you do any test to validate your supposition? 

Nonetheless, I don't think a production deployment should set `generateAdmissionControllerCerts` to true and rather use Cert-Manager if possible.

**Comment by hochuenw-dd** [comment]
Hi @phisco , I simply updated the resources.requests.cpu in values.yaml and noticed the caBundle in the webhookconfiguration is changed.

**Comment by phisco** [comment]
Ok, so, the only problem would be with resources being applied during a multi-replicas open-policy-agent webhook rollout. That could be considered acceptable, in my opinion. 

I still think you should not use the `generateAdmissionControllerCerts` functionality in prod, so I'm not sure we should dig deeper into how to avoid that. If you don't want your certificate regenerated you should just pass your own or use Cert-manager.

In case we wanted to address this, we could use the helm `lookup` function to check whether the CA has already been generated or not, if you want to give it a try feel free to open a PR.
