### ISSUE TITLE
Reuse Kubernetes client across replicated resources

### ISSUE THREAD

**Issue by tallclair** [open-policy-agent/kube-mgmt#99]
Is there a reason that kube-mgmt creates a new kubernetes client for each replicated resource type? I think it should be more efficient to create a single Kubernetes client that's used for all k8s api requests.

**Comment by tsandall** [comment]
> Is there a reason that kube-mgmt creates a new kubernetes client for each replicated resource type? 

No particular reason.

> I think it should be more efficient to create a single Kubernetes client that's used for all k8s api requests.

It hasn't been an issue AFAIK but if you'd like to submit a PR, that would be great.
